[package]
name = "orderbook"
version = "0.1.0"
authors = ["Alessio Artoni <alessio@artoni.org>"]
edition = "2018"

[dependencies]
csv = "1.1"
rb_tree = { version = "0.5", default-features = false, features = ["map"] }
